on:
  push:
     branches:
      master

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Set up old Java Oracle'
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'oracle'
    - name: Install dependencies
      run: mvn -q instal l -Dgpg.skip
    - name: Maven built
      run: mvn -q clean compile test
    - name: Curl Code
      if: ${{ success() }}
      run: bash <(curl -s https://codecov.io/bash)
    - name: Cache
      uses: actions/cache@v3
      with:
          key: ${{ runner.os }}-m2
          path: $HOME/.m2
